### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by alexmcroberts** [yvecai/data-opensnowmap.org#1]
Would you be willing to write a readme.md in order to get an instance of this running locally?

**Comment by DFyson** [comment]
I would also really appreciate some documentation for these scripts. It'd be nice to have an idea of what each script can do and how to use it instead of having to figure it out from the code.

**Comment by yvecai** [comment]
Added readme.md.

**Comment by alexmcroberts** [comment]
@yvecai thanks a lot! this is great!
